<?php
if (session_status() === PHP_SESSION_NONE) {
	session_start();
}
require_once __DIR__ . '/conexion.php';
require_once __DIR__ . '/helpers/autorizacion.php';
$usuario = sigtur_requerir_rol($pdo, ['organizador'], 'login.php', 'eventos.php');
$csrfToken = sigtur_csrf_token();
$eventosStmt = $pdo->prepare('SELECT id, titulo, descripcion, fecha, ubicacion, categoria, tipo_entrada, precio, imagen_portada FROM eventos WHERE organizador_id = :organizador ORDER BY fecha ASC');
$eventosStmt->execute([':organizador' => (int) $usuario['id']]);
$eventos = $eventosStmt->fetchAll();
$consultasStmt = $pdo->prepare('SELECT p.id, p.pregunta, p.respuesta, p.fecha_creacion, e.titulo, e.id AS evento_id, u.nombre_completo FROM preguntas_eventos p INNER JOIN eventos e ON e.slug = p.evento_slug INNER JOIN usuarios u ON u.id = p.usuario_id WHERE e.organizador_id = :organizador ORDER BY p.fecha_creacion DESC');
$consultasStmt->execute([':organizador' => (int) $usuario['id']]);
$consultas = $consultasStmt->fetchAll();
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Panel de organizador | SIGTUR</title><link rel="stylesheet" href="../css/estilos.css"><style>
body{background:#f4f6f8;color:#18212a}.panel{max-width:1180px;margin:0 auto;padding:2rem 1.25rem 5rem}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin-bottom:2rem}.panel-head h1{margin:0}.panel-links,.actions{display:flex;flex-wrap:wrap;gap:.6rem}.panel a,.panel button{font:inherit}.panel-link,.save,.delete,.reply{display:inline-block;border:0;border-radius:8px;padding:.7rem 1rem;text-decoration:none;font-weight:700;cursor:pointer}.panel-link,.save,.reply{background:#152d3d;color:#fff}.delete{background:#ffe9e5;color:#a53628}.event-card,.query{margin:1rem 0;padding:1.2rem;background:#fff;border:1px solid #dce3e8;border-radius:8px}.event-card h3,.query h3{margin:.1rem 0 1rem}.event-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}.event-form label,.query-form label{display:grid;gap:.3rem;font-weight:600}.event-form input,.event-form textarea,.event-form select,.query-form textarea{width:100%;padding:.65rem;border:1px solid #cbd4db;border-radius:6px;font:inherit}.event-form textarea{min-height:90px}.wide{grid-column:1/-1}.muted{color:#65727d}.query-form{display:grid;gap:.7rem}.empty{padding:1rem 0;color:#65727d}@media(max-width:680px){.panel-head{align-items:flex-start;flex-direction:column}.event-form{grid-template-columns:1fr}.wide{grid-column:auto}}
</style></head><body><main class="panel"><header class="panel-head"><div><p class="muted">SIGTUR · Organizador</p><h1>Panel de organizador</h1><p>Gestiona tus eventos y responde las consultas relacionadas.</p></div><nav class="panel-links"><a class="panel-link" href="eventos.php">Ver eventos</a><a class="panel-link" href="../index.php">Inicio</a></nav></header>
<section><h2>Mis eventos</h2><?php if (!$eventos): ?><p class="empty">Todavía no tienes eventos. Puedes crear uno desde <a href="eventos.php">Eventos</a>.</p><?php endif; ?>
<?php foreach ($eventos as $evento): ?><article class="event-card"><h3><?= htmlspecialchars($evento['titulo'], ENT_QUOTES, 'UTF-8') ?></h3><form class="event-form" method="post" action="crear-evento.php"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="accion" value="editar"><input type="hidden" name="evento_id" value="<?= (int) $evento['id'] ?>"><label>Título<input name="titulo" maxlength="255" required value="<?= htmlspecialchars($evento['titulo'], ENT_QUOTES, 'UTF-8') ?>"></label><label>Fecha<input type="date" name="fecha" required value="<?= htmlspecialchars($evento['fecha'], ENT_QUOTES, 'UTF-8') ?>"></label><label>Ubicación<input name="ubicacion" maxlength="255" required value="<?= htmlspecialchars($evento['ubicacion'], ENT_QUOTES, 'UTF-8') ?>"></label><label>Categoría<input name="categoria" maxlength="100" required value="<?= htmlspecialchars($evento['categoria'], ENT_QUOTES, 'UTF-8') ?>"></label><label>Tipo de entrada<select name="tipoEntrada"><option value="Gratuito" <?= $evento['tipo_entrada'] === 'Gratuito' ? 'selected' : '' ?>>Gratuito</option><option value="De Pago" <?= $evento['tipo_entrada'] === 'De Pago' ? 'selected' : '' ?>>De Pago</option></select></label><label>Precio<input type="number" min="0" step="0.01" name="precio" value="<?= htmlspecialchars((string) ($evento['precio'] ?? ''), ENT_QUOTES, 'UTF-8') ?>"></label><label class="wide">Descripción<textarea name="descripcion" required><?= htmlspecialchars($evento['descripcion'], ENT_QUOTES, 'UTF-8') ?></textarea></label><label class="wide">Ruta de imagen<input name="imagen_portada" maxlength="255" value="<?= htmlspecialchars($evento['imagen_portada'], ENT_QUOTES, 'UTF-8') ?>"></label><div class="wide actions"><button class="save" type="submit">Guardar cambios</button><a class="panel-link" href="evento.php?id=<?= (int) $evento['id'] ?>">Abrir evento</a></div></form><form method="post" action="crear-evento.php" onsubmit="return confirm('¿Eliminar este evento? Esta acción no se puede deshacer.')"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="accion" value="eliminar"><input type="hidden" name="evento_id" value="<?= (int) $evento['id'] ?>"><button class="delete" type="submit">Eliminar evento</button></form></article><?php endforeach; ?></section>
<section id="consultas"><h2>Consultas de mis eventos</h2><?php if (!$consultas): ?><p class="empty">Aún no hay consultas vinculadas a tus eventos.</p><?php endif; ?><?php foreach ($consultas as $consulta): ?><article class="query"><h3><?= htmlspecialchars($consulta['titulo'], ENT_QUOTES, 'UTF-8') ?></h3><p><strong><?= htmlspecialchars($consulta['nombre_completo'], ENT_QUOTES, 'UTF-8') ?>:</strong> <?= nl2br(htmlspecialchars($consulta['pregunta'], ENT_QUOTES, 'UTF-8')) ?></p><?php if ($consulta['respuesta']): ?><p><strong>Respuesta:</strong> <?= nl2br(htmlspecialchars($consulta['respuesta'], ENT_QUOTES, 'UTF-8')) ?></p><?php endif; ?><form class="query-form" method="post" action="api/responder_consulta_evento.php"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="pregunta_id" value="<?= (int) $consulta['id'] ?>"><label>Responder<textarea name="respuesta" maxlength="2000" required><?= htmlspecialchars($consulta['respuesta'] ?? '', ENT_QUOTES, 'UTF-8') ?></textarea></label><button class="reply" type="submit">Enviar respuesta</button></form></article><?php endforeach; ?></section></main></body></html>